-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 15:18:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`editoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editoras` (
  `ideditoras` INT NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `idcontato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideditoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livros` (
  `idLivros` INT NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `ISBN` CHAR(13) NOT NULL,
  `idmuta` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `editoras_ideditoras` INT NOT NULL,
  PRIMARY KEY (`idLivros`),
  INDEX `fk_Livros_editoras1_idx` (`editoras_ideditoras` ASC) VISIBLE,
  CONSTRAINT `fk_Livros_editoras1`
    FOREIGN KEY (`editoras_ideditoras`)
    REFERENCES `mydb`.`editoras` (`ideditoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `realizaremprestimo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contatotelefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contatotelefone` (
  `idcontatotelefone` INT NOT NULL,
  `idcliente` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `DDI` VARCHAR(3) NULL,
  `DDD` VARCHAR(3) NULL,
  `idtipodecontato` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontatotelefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `endereço` VARCHAR(50) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `pediremprestimo` VARCHAR(45) NOT NULL,
  `contatotelefone_idcontatotelefone` INT NOT NULL,
  `contatotelefone_idcontatotelefone1` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `contatotelefone_idcontatotelefone`),
  INDEX `fk_cliente_contatotelefone1_idx` (`contatotelefone_idcontatotelefone1` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_contatotelefone1`
    FOREIGN KEY (`contatotelefone_idcontatotelefone1`)
    REFERENCES `mydb`.`contatotelefone` (`idcontatotelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `idemprestimo` INT NOT NULL,
  `multa` DATETIME NOT NULL,
  `idcliente` VARCHAR(45) NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `cliente_contatotelefone_idcontatotelefone` INT NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`cliente_idcliente` ASC, `cliente_contatotelefone_idcontatotelefone` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`cliente_idcliente` , `cliente_contatotelefone_idcontatotelefone`)
    REFERENCES `mydb`.`cliente` (`idcliente` , `contatotelefone_idcontatotelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logradouro` (
  `idlogradouro` INT NOT NULL,
  `DATA` DATETIME NOT NULL,
  `idcliente` VARCHAR(45) NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipolagradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipolagradouro` (
  `idtipolagradouro` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipolagradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereço` (
  `idendereço` INT NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `NomeLogradouro` VARCHAR(50) NOT NULL,
  `NumEndereço` CHAR(6) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `pontoRef` VARCHAR(100) NULL,
  `cliente_idcliente` INT NOT NULL,
  `cliente_contatotelefone_idcontatotelefone` INT NOT NULL,
  `cliente_idcliente1` INT NOT NULL,
  `cliente_contatotelefone_idcontatotelefone1` INT NOT NULL,
  `tipolagradouro_idtipolagradouro` INT NOT NULL,
  PRIMARY KEY (`idendereço`, `cliente_idcliente`, `cliente_contatotelefone_idcontatotelefone`),
  INDEX `fk_endereço_cliente1_idx` (`cliente_idcliente1` ASC, `cliente_contatotelefone_idcontatotelefone1` ASC) VISIBLE,
  INDEX `fk_endereço_tipolagradouro1_idx` (`tipolagradouro_idtipolagradouro` ASC) VISIBLE,
  CONSTRAINT `fk_endereço_cliente1`
    FOREIGN KEY (`cliente_idcliente1` , `cliente_contatotelefone_idcontatotelefone1`)
    REFERENCES `mydb`.`cliente` (`idcliente` , `contatotelefone_idcontatotelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereço_tipolagradouro1`
    FOREIGN KEY (`tipolagradouro_idtipolagradouro`)
    REFERENCES `mydb`.`tipolagradouro` (`idtipolagradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipodecontato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipodecontato` (
  `idtipodecontato` INT NOT NULL,
  `NomeTipodecontato` VARCHAR(45) NOT NULL,
  `contatotelefone_idcontatotelefone` INT NOT NULL,
  PRIMARY KEY (`idtipodecontato`),
  INDEX `fk_tipodecontato_contatotelefone1_idx` (`contatotelefone_idcontatotelefone` ASC) VISIBLE,
  CONSTRAINT `fk_tipodecontato_contatotelefone1`
    FOREIGN KEY (`contatotelefone_idcontatotelefone`)
    REFERENCES `mydb`.`contatotelefone` (`idcontatotelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL,
  `tipo_de_genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Generolivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Generolivro` (
  `idgenero` INT NOT NULL,
  `idlivro` INT NOT NULL,
  PRIMARY KEY (`idgenero`, `idlivro`),
  CONSTRAINT `idgenero`
    FOREIGN KEY (`idgenero`)
    REFERENCES `mydb`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idlivro`
    FOREIGN KEY (`idgenero` , `idlivro`)
    REFERENCES `mydb`.`Livros` (`idLivros` , `idLivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
